apiVersion: v1
kind: Service
metadata:
  name: triton-inference-server
  namespace: triton
  labels:
    app: triton
spec:
  type: LoadBalancer
  ports:
    - name: http-inference
      port: 8000
      targetPort: 8000
    - name: grpc-inference
      port: 8001
      targetPort: 8001
    - name: metrics
      port: 8002
      targetPort: 8002
  selector:
    app: triton
